### ISSUE TITLE
AFP Contribution

### ISSUE THREAD

**Issue by benkeks** [luisamontanari/ContrasimGame#5]
Guidelines: https://www.isa-afp.org/submission/
Timeframe: Some time in 2023-06

**Comment by benkeks** [comment]
@luisamontanari I've now integrated the theory with my 2019 theory of coupled similarity, added an intro, and refined some aspects of the presentation.

Please have a look whether there are things you want to improve before submission to the AFP! :)

**Comment by luisamontanari** [comment]
@benkeks thanks a lot for all of your work! I've only changed a few minor things here and there to improve readability and consistency. I think we're ready for the AFP contribution ;)

**Comment by benkeks** [comment]
@luisamontanari Thanks!

Now that you went into naming... It would be nice to align the naming of `Basic_Contrasim_Game` and `Contrasim_Set_Game`. For instance, the first could be renamed to `Contrasim_Word_Game` (with names of sections changed accordingly).

I've also renamed the session to `Coupledsim_Contrasim` and the document title to “Coupled Similarity and Contrasimilarity, and How to Compute Them”.

**Comment by benkeks** [comment]
I added some more explanations and such. I think, I'm finished now. Have you checked whether you like the big-picture introduction in https://luisamontanari.github.io/ContrasimGame/Unsorted/Coupledsim_Contrasim/document.pdf @luisamontanari ?

**Comment by benkeks** [comment]
Submitted.
